#!/bin/bash
# Originally by Sean Buckley, sean.bck@gmail.com
set -ex

TARGETPART="/dev/vda"

echo "This will install kexec and reboot to the arch iso. Press [Enter] to continue."
read a

pacman --noconfirm -Sy kexec-tools

mount /arch.iso /mnt
#cp -r /mnt/arch /
cp -r /mnt/arch /tmp/
umount /mnt

while ! mount -o ro,remount / ;do
    systemctl stop systemd-journald || true
    sleep 1
done

kexec --load "/tmp/arch/boot/`uname -m`/vmlinuz" --initrd="/tmp/arch/boot/`uname -m`/archiso.img" --append="archisodevice=$TARGETPART copytoram=y"
kexec -e
