#!/bin/bash

# block until internet works
while ! ping -c 1 -W 1 8.8.8.8 >/dev/null; do echo notyet ; sleep 1 ; done

firefox &

pidgin &
#teamspeak3 &
mumble &
spotify &
#torchat &

#xterm -e "ses" &

#bitcoin-qt &

thunderbird &

