#!/bin/bash

DATAUSER="mal"

if [ "`whoami`" != "root" ] ; then
    echo "Need elevation!"
    exec sudo $0 $@
fi

case $@ in
    "")
        echo "Specify a machine to back up, or \"all\"."
        exit
        ;;
    all)
        STUFFTOBU="luca eva blake pluto tron"
        ;;
    *)
        STUFFTOBU="$@"
        ;;
esac

START=$(date +%s)

ARGS="-aXEhzAy --info=progress2 --delete --delete-delay --exclude-from /home/$DATAUSER/.bin/data/backup.exclude.txt -v"
BUDIR="/mnt/bulk/backups"
SSHARGS="-i /home/$DATAUSER/.ssh/id_rsa -F /home/$DATAUSER/.ssh/config"

for butarget in $STUFFTOBU ; do
    echo -n "[Enter] to start $butarget:"
    read junk
    case $butarget in
        luca)
            rsync $ARGS / $BUDIR/$butarget
            ;;
        eva|blake|pluto)
            rsync -4 $ARGS -e "ssh $SSHARGS" root@${butarget}.sec.gd:/ $BUDIR/$butarget
            ;;
        tron)
            rsync -4 $ARGS -e "ssh $SSHARGS" root@tron.disruptivelabs.org:/ $BUDIR/$butarget
            ;;
        *)
            echo "Invalid backup target!"
            ;;
    esac
    echo "Backup from $(date '+%A, %d %B %Y, %T')" >$BUDIR/${butarget}.backupinfo.txt
done

FINISH=$(date +%s)
echo " time: $(( ($FINISH-$START) / 60 )) minutes, $(( ($FINISH-$START) % 60 )) seconds"

df -h $BUDIR

