#!/bin/bash

# Use this user's .ssh/config etc
DATAUSER="mal"
KEEPDAYS=7
KEEPWEEKS=26 # 26=6mos
BUDIR="/mnt/bulk/backups"
ARGS="-aHAEXhyy --numeric-ids --info=progress2 --delete --delete-delay --exclude-from /home/$DATAUSER/.bin/data/backup.exclude.txt"

if [ "`whoami`" != "root" ] ; then
    echo "Need elevation!"
    exec sudo $0 $@
fi

case $@ in
    "")
        echo "Specify a machine to back up, or \"all\"."
        exit
        ;;
    all)
        STUFFTOBU="luca nova mars"
        ;;
    *)
        STUFFTOBU="$@"
        ;;
esac

START=$(date +%s)
SSHARGS="-F /home/$DATAUSER/.ssh/config"

for butarget in $STUFFTOBU ; do
    echo -n "[Enter] to start $butarget:"
    read junk
    now="`date '+%Y%m%d.%H%M%S.%a'`"
    last="`ls ${BUDIR}/$butarget | sort | tail -n 1`"
    hl="--link-dest=${BUDIR}/$butarget/$last"
    case $butarget in
        luca)
            rsync $ARGS / $BUDIR/$butarget/$now/ $hl
            ;;
        nova|blake|mars|xps)
            rsync -4 $ARGS -z -e "ssh $SSHARGS" root@${butarget}.sec.gd:/ $BUDIR/$butarget/$now/ $hl
            ;;
        *)
            echo "Invalid backup target!"
            ;;
    esac
    # Delete all but the most recent $KEEPDAYS. Ignore weeklies.
    for backup in `ls "${BUDIR}/$butarget" | sort | head -n -${KEEPDAYS} | grep -vE '\.Mon$'` ; do
            echo "Removing old daily: ${backup}"
            echo rm -rf "${BUDIR}/$butarget/${backup}"
    done
    # Delete old weeklies - only works if run every     Mon
    for backup in `ls "${BUDIR}/$butarget" | grep -E '\.Mon$' | sort | head -n -${KEEPWEEKS}` ; do
            echo "Removing old weekly: ${backup}"
            echo rm -rf "${BUDIR}/$butarget/${backup}"
    done
done

FINISH=$(date +%s)
echo " time: $(( ($FINISH-$START) / 60 )) minutes, $(( ($FINISH-$START) % 60 )) seconds"

df -h $BUDIR
