#!/bin/bash

now="`date +%s`"
xsize="`xrandr | grep '*' | awk '{print $1}'`"

#arecord -r 192 >./out/$now.wav &
arecord -f cd ./out/$now.wav -r 48000 &

ffmpeg -r 60 -f x11grab -s "$xsize" -i :0.0 -vcodec libx264 -preset ultrafast ./out/$now.mkv

kill -2 $!

