#!/bin/bash

EXTIF="eth0"
EXTIF6="sixxs"
INTIF="tun0"
INTIFCTF="tun1"
LOGDROPLIMIT="2/s"
LOGDROPLIMITBURST="10"

cat >/etc/iptables/iptables.rules.new  <<EOF
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:sshguard - [0:0]

-N LOGDROP
-A LOGDROP -p tcp -m limit --limit $LOGDROPLIMIT --limit-burst $LOGDROPLIMITBURST -j LOG --log-prefix "TCP LOGDROP: "
-A LOGDROP -p udp -m limit --limit $LOGDROPLIMIT --limit-burst $LOGDROPLIMITBURST -j LOG --log-prefix "UDP LOGDROP: "
-4 -A LOGDROP -p icmp   -m limit --limit $LOGDROPLIMIT --limit-burst $LOGDROPLIMITBURST -j LOG --log-prefix "ICMP LOGDROP: "
-6 -A LOGDROP -p icmpv6 -m limit --limit $LOGDROPLIMIT --limit-burst $LOGDROPLIMITBURST -j LOG --log-prefix "ICMP LOGDROP: "
-4 -A LOGDROP -f -m limit --limit $LOGDROPLIMIT --limit-burst $LOGDROPLIMITBURST -j LOG --log-prefix "FRAGMENT LOGDROP: "
-A LOGDROP -j DROP

-N LOGACCEPT
-A LOGACCEPT -p tcp -j LOG --log-prefix "TCP LOGACCEPT: "
-A LOGACCEPT -p udp -j LOG --log-prefix "UDP LOGACCEPT: "
-4 -A LOGACCEPT -p icmp   -j LOG --log-prefix "ICMP LOGACCEPT: "
-6 -A LOGACCEPT -p icmpv6 -j LOG --log-prefix "ICMP LOGACCEPT: "
-4 -A LOGACCEPT -f -j LOG --log-prefix "FRAGMENT LOGACCEPT: "
-A LOGACCEPT -j ACCEPT

# Bad v6 Stuff
-6 -A INPUT   -m rt --rt-type 0 -j DROP
-6 -A FORWARD -m rt --rt-type 0 -j DROP
-6 -A OUTPUT  -m rt --rt-type 0 -j DROP

# Loopback is always okay
-A INPUT -i lo -j ACCEPT

# Internal network traffic is always okay
-A INPUT -i $INTIF -j ACCEPT

# Any incoming not headed for the external IP drop (actually I don't want to
# need EXTIP if I don't need it )
#-4 -A INPUT -i $EXTIF  ! -d $EXTIP  -j DROP
#-6 -A INPUT -i $EXTIF6 ! -d $EXTIP6 -j DROP

# SSHGuard, block all traffic from sources that trip sshguard
-A INPUT -j sshguard

# Existing connections are fine
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# ICMP
-4 -A INPUT -p icmp   -j ACCEPT
-6 -A INPUT -p icmpv6 -j ACCEPT

# SSH server
-A INPUT -p tcp --dport 22 -j ACCEPT

# SMTP incoming
-A INPUT -p tcp --dport 25 -j ACCEPT

# DNS server
-A INPUT -p tcp --dport 53 -j ACCEPT
-A INPUT -p udp --dport 53 -j ACCEPT

# ident
-A INPUT -p tcp --dport 113 -j ACCEPT

# HTTP/S server
-A INPUT -p tcp --dport  80 -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT

# SMTP/TLS outgoing
-A INPUT -p tcp --dport 465 -j ACCEPT

# IMAP/TLS server
-A INPUT -p tcp --dport 993 -j ACCEPT

# OpenVPN server
-A INPUT -p tcp --dport 1194 -j ACCEPT
-A INPUT -p udp --dport 1194 -j ACCEPT

# IRC server
-A INPUT -p tcp --dport 6697 -j ACCEPT

# TOR
-A INPUT -p tcp --dport 9909 -j ACCEPT
-A INPUT -p udp --dport 9909 -j ACCEPT
-A INPUT -p tcp --dport 9939 -j ACCEPT
-A INPUT -p udp --dport 9939 -j ACCEPT

# Teamspeak server
-A INPUT -p udp --dport  9987 -j ACCEPT
-A INPUT -p tcp --dport 30033 -j ACCEPT

# CJDNS
-A INPUT -p udp --dport 15069 -j ACCEPT

# mosh
-A INPUT -p udp --dport 60000:61000 -j ACCEPT

# murmur
-A INPUT -p tcp --dport 64738 -j ACCEPT
-A INPUT -p udp --dport 64738 -j ACCEPT



# Forwarding existing connections is fine
-A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Internal network to universe is fine
-A FORWARD -i $INTIF -j ACCEPT

# Port forwards
-A FORWARD -o $INTIFCTF -p tcp --dport 22 -j ACCEPT

# Don't forward traffic from outside to outside
-A FORWARD -i $EXTIF -o $EXTIF -j DROP
-A FORWARD -i $INTIFCTF -o $INTIFCTF -j DROP
-A FORWARD -i $EXTIF6 -o $EXTIF6 -j DROP



# Fuck t-mobile and their dns hijacking
-4 -A OUTPUT -d lookup.t-mobile.com -j REJECT



COMMIT

*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]

# Masquerade outgoing for NAT
-A POSTROUTING ! -o lo -j MASQUERADE

# Port forwards
-4 -A PREROUTING -p tcp --dport 23 -j DNAT --to 10.194.0.45:22


COMMIT
EOF

cat <<EOF
- Enable failsafe in crontab
- Use iptables-restore AND ip6tables-restore on /etc/iptables/iptables.rules.new
- Test stuff
- Move iptables.rules.new to iptables.rules
- Turn off crontab failsafe
- Restart sshguard so it'll re-block continuing offenders
EOF

