#!/bin/bash

# This file exists solely so the .desktop file for FTB can be run from steam
# Steam doesn't seem to care about arguments, so this file defaults to FTB

java="java"
jopts="-Xmx2G -Xincgc"

case $1 in
    ftb|feedthebeast|*)
        cd ~/.bin/data/
        exec $java -jar FTB_Launcher.jar
        ;;
    spout|spoutcraft)
        cd ~/.spoutcraft/
        exec $java -jar Spoutcraft.jar
        ;;
    mc|minecraft)
        cd ~/.bin/data/
        exec $java $jopts -jar minecraft.jar
        ;;
esac

