#!/bin/bash
# Sets up monitors for convenient use over VNC
# by mal@sec.gd

case $1 in
    normal)
        xrandr -d :0.0 --screen 0 --output DVI-I-2 --auto --scale-from 1920x1080 --output DVI-I-1 --auto --pos 1920x56
        ;;
    vnc)
        xrandr -d :0.0 --screen 0 --output DVI-I-1 --off --output DVI-I-2 --scale-from 1280x720
        ;;
    vnc2)
        xrandr -d :0.0 --screen 0 --output DVI-I-1 --off --fb 1280x960 --output DVI-I-2 --mode 1280x960
        ;;
    *)
        echo "Usage: $0 [normal|vnc]"
        ;;
esac

