#!/bin/bash

SESNAME=ses

tmux has-session -t $SESNAME 2>&1 >/dev/null
if [ $? -eq 0 ]; then
    tmux a -t $SESNAME
    exit 0;
fi


tmux new-session -d -s $SESNAME
tmux a -t $SESNAME &
tmux send-keys -t $SESNAME 'ssh minecraft@mc.bck.me' C-m
tmux send-keys -t $SESNAME 'mcr a' C-m
tmux split-window -h -t $SESNAME
tmux send-keys -t $SESNAME 'htop' C-m
tmux split-window -t $SESNAME
#tmux send-keys -t $SESNAME 'ssh -D 8081 maya.blackcatstudios.org' C-m
#tmux send-keys -t $SESNAME 'htop' C-m
tmux select-pane -t :.+ -t $SESNAME
tmux select-pane -t :.+ -t $SESNAME
#tmux split-window -t $SESNAME
#tmux send-keys -t $SESNAME 'fah' C-m
#tmux split-window -t $SESNAME
#tmux send-keys -t $SESNAME 'fah-gpu' C-m
#tmux select-pane -t :.+ -t $SESNAME
#tmux select-pane -t :.+ -t $SESNAME

tmux a -t $SESNAME
