#!/bin/bash

export WINEPREFIX="$HOME/.local/share/wineprefixes/steam"
export WINEARCH=win32
export WINEDEBUG="" # fixme-all

case $1 in
    run)
        shift
        exec "$@"
        ;;
    install)
        #winetricks --no-isolate steam
        winetricks corefonts
        wget -o /dev/null -O /tmp/SteamInstall.msi http://cdn.steampowered.com/download/SteamInstall.msi
        exec wine msiexec /i /tmp/SteamInstall.msi
        ;;
    fixfonts)
        cat >/tmp/steamfixfonts.reg <<EOF
[HKEY_CURRENT_USER\Control Panel\Desktop]
"FontSmoothing"="2"
"FontSmoothingType"=dword:00000002
"FontSmoothingGamma"=dword:00000578
"FontSmoothingOrientation"=dword:00000001
EOF
        env WINEDEBUG="$WINEDEBUG" exec wine regedit fontfix.reg
        ;;
    ""|args)
        shift
        exec wine "C:\Program Files\Steam\steam.exe" -no-dwrite $@
        ;;
    help|*)
        echo "Run with no arguments to start steam, OR one of:
            args [stuff]        Passes [stuff] to steam.exe
            run [command]       Run [command] for steam prefix
            install             Download and install steam
            fixfonts            Apply patch to make fonts look better
            help                This garbage"
        ;;
esac

