#!/bin/bash

export WINEPREFIX="$HOME/.local/share/wineprefixes/steam"
export WINEARCH=win32
export WINEDEBUG="fixme-all" # fixme-all disable all fixme, warn+all enable all warn, etc

case $1 in
    run)
        shift
        exec "$@"
        ;;
    install)
        #winetricks --no-isolate steam
        winetricks corefonts
        wget -o /dev/null -O /tmp/SteamInstall.msi http://cdn.steampowered.com/download/SteamInstall.msi
        exec wine msiexec /i /tmp/SteamInstall.msi
        ;;
    fixfonts)
        cat >/tmp/steamfixfonts.reg <<EOF
[HKEY_CURRENT_USER\Control Panel\Desktop]
"FontSmoothing"="2"
"FontSmoothingType"=dword:00000002
"FontSmoothingGamma"=dword:00000578
"FontSmoothingOrientation"=dword:00000001
EOF
        env WINEDEBUG="$WINEDEBUG" exec wine regedit fontfix.reg
        ;;
    ""|args|game)
        if [ "x$1" == "xgame" ] ; then
            shift
            ins="steam://run"
            case $1 in
                torchlight)
                    ins=$ins/200710
                    ;;
                portal)
                    ins=$ins/400
                    ;;
                portal2)
                    ins=$ins/620
                    ;;
                tf2)
                    ins=$ins/440
                    ;;
                gtaiv)
                    ins=$ins/12210
                    ;;
                gtaiveflc)
                    ins=$ins/12220
                    ;;
                *)
                    echo "App not found, trying to run anyway."
                    ins=$ins/$1
                    ;;
            esac
        fi
        shift
        exec wine 'C:\Program Files\Steam\steam.exe' -no-dwrite $ins $@
        ;;
    help|*)
        echo "Run with no arguments to start steam, OR one of:
            game [gamename]     Try to run the specified game
            args [stuff]        Passes [stuff] to steam.exe
            run [command]       Run [command] for steam prefix
            install             Download and install steam
            fixfonts            Apply patch to make fonts look better
            help                This garbage"
        ;;
esac

