#!/bin/bash -ex

if [ -z "$XDG_DATA_HOME" ] ; then
    echo "Invalid XDG_DATA_HOME"
    exit 3
fi

workdir="$XDG_DATA_HOME/TelegramDesktopAlt$1/"
[ -d "$workdir" ] || mkdir -p $workdir

exec telegram-desktop -many -workdir "$workdir"
