#!/bin/bash

date1=$(date +"%s")
date2=$(date --date="August 26, 2014 15:30" +"%s")
diff=$(($date2-$date1))
weeks=$(($diff / 604800))
weeks_days=$(($diff % 604800 / 86400))
days=$(($diff / 86400))
days_hours=$(($diff % 86400 / 3600))
hours_minutes=$(($diff % 3600 / 60))
echo -e "$weeks weeks, $weeks_days days to freedom!\nThat's $days days total." | mutt -s "$weeks weeks, $weeks_days days to freedom!" "mal@sec.gd" 2>&1 >/dev/null
#rm -f sent

